backend:
  name: github
  repo: tech4him1/netlify-cms-example
  branch: master

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "post"
    label: "Post"
    folder: "content/post"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "List", name: "list", widget: "list"}
      - {label: "Select", name: "select", widget: "select"}
      - {label: "Relation", name: "relation", widget: "relation"}
      - {label: "Body", name: "body", widget: "markdown"}
